export type AllNavParamList = {
  SplashScreen: undefined;
  Onboarding: undefined;
  OtpScreen: undefined;
  Login: undefined;
  SignUp: undefined;
  AccountSuccess: undefined;
  ForgotPassword: undefined;
  ResetPassword: { email: string };
  PasswordSuccess: undefined;
  VerifyOtp: { from: string; email?: string };
  Dashboard: undefined;
  HomeStack: undefined;
  Home: undefined;
  NotificationScreen: undefined;
  Reports: undefined;
  Budgets: undefined;
  TransactionStack: undefined;
  Transactions: undefined;
  SettingStack: undefined;
  Setting: undefined;
  ProfileScreen: undefined;
  Currency: undefined;
  Profile: undefined;
  ChangePassword: undefined;
  PrivacyPolicy: undefined;
  TermsCondition: undefined;
  FAQ: undefined;
};
